# Generated by Django 4.2.5 on 2023-10-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=30)),
                ('Image', models.ImageField(default='null.jpg', upload_to='Image')),
            ],
        ),
    ]
