# Generated by Django 4.2.5 on 2023-10-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_catalogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='country',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='genre',
        ),
    ]
