# Generated by Django 4.2.5 on 2023-10-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_categories_country_remove_categories_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
