# Generated by Django 4.2.5 on 2023-10-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
