# Generated by Django 4.2.5 on 2023-10-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_categories_choose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
