# Generated by Django 4.2.5 on 2023-10-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_delete_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='null.jpg', upload_to='image')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=30)),
                ('releaseyear', models.IntegerField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('quality', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=20)),
                ('tvseries', models.CharField(max_length=10)),
                ('music', models.CharField(max_length=10)),
                ('video', models.FileField(default='null.mkv', upload_to='video')),
                ('link', models.CharField(max_length=20)),
                ('movie', models.CharField(max_length=20)),
            ],
        ),
    ]
