# Generated by Django 4.2.5 on 2023-10-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='music',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='tvseries',
        ),
    ]
