# Generated by Django 4.2.5 on 2023-11-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_categories_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='audio',
            field=models.FileField(default='null.mp3', upload_to='audio'),
        ),
    ]
