# Generated by Django 4.2.5 on 2023-11-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='free_trial',
        ),
    ]
