# Generated by Django 4.2.5 on 2023-11-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_remove_subscriptionplan_free_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
