# Generated by Django 4.2.5 on 2023-11-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_subscribed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_users',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
