# Generated by Django 4.2.5 on 2023-11-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_subscribed_users_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='validity',
            field=models.IntegerField(),
        ),
    ]
