# Generated by Django 4.2.5 on 2023-10-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Register',
        ),
    ]
