# Generated by Django 4.2.5 on 2023-11-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0002_rename_signup_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singlearea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=20)),
                ('tvseries', models.CharField(max_length=20)),
                ('music', models.CharField(max_length=20)),
            ],
        ),
    ]
