# Generated by Django 4.2.5 on 2023-11-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('textarea', models.TextField()),
                ('areas', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
