# Generated by Django 4.2.5 on 2023-11-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
