# Generated by Django 4.2.5 on 2023-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
