# Generated by Django 4.2.5 on 2023-11-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0009_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
