# Generated by Django 4.2.5 on 2023-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0010_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('validity', models.CharField(max_length=20)),
                ('features', models.CharField(max_length=200)),
                ('free_trial', models.IntegerField(default=0)),
                ('payment_method', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
