# Generated by Django 4.2.5 on 2023-11-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flixapp', '0011_subscriptionplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
